#!/bin/sh

function join_by {
    local IFS="$1";
    shift;
    echo "$*";
}

function filter_existing_files {
    local files=$1
    local existing_files=()
    for file in $files; do
        if [ -f "$file" ]; then
            existing_files+=("$file")
        fi
    done
    echo "${existing_files[@]}"
}

files=$(git diff --cached --name-only)
files=$(filter_existing_files "$files")
esbuildFiles=$(echo "$files" | grep -i -E '.*\.(js|ts|svelte)' | join_by " ")
joinedFiles=$(join_by " " $files)
echo Changed Files: $(joinedFiles)
echo "Changed Files: $joinedFiles" > "D:/github-repos/clouser-studios/utility-engine-blockbench-plugin/commit-staged-out.txt"

if [ -z "$files" ]; then
    echo "Commit has no changes!"
    exit 1
fi
# Check for merge markers in modified files
for file in $files; do
    if grep -q -E '^(<<<<<<<|=======|>>>>>>>|\|\|\|\|\|\|\|)$' "$file"; then
        echo "Error: File '$file' contains merge markers. Please remove them before committing."
        exit 1
    fi
done

set -e

npx prettier --check $joinedFiles
npx eslint --max-warnings=0 --no-warn-ignored $esbuildFiles
echo "ESLint and Prettier checks passed successfully!"

# Exit with success if there are no errors
exit 0
